import type { WorkflowDef, ScriptDef } from './types'

export const WORKFLOWS: WorkflowDef[] = [
  {
    id: 'cluster-create',
    name: 'Cluster Create',
    description: 'Creates clusters using Foundation Central with full node imaging',
    category: 'Infrastructure',
    icon: 'Server',
    configFile: 'create_cluster.yml',
    details: 'Automates the complete cluster creation process including node discovery, AOS/AHV imaging, and cluster formation through Foundation Central. Supports both DHCP and static IP configurations.',
  },
  {
    id: 'imaging-only',
    name: 'Imaging Only',
    description: 'Images nodes without creating a cluster (bare metal prep)',
    category: 'Infrastructure',
    icon: 'HardDrive',
    configFile: 'imaging_only.yml',
    details: 'Images Nutanix nodes with the specified AOS and hypervisor versions without forming clusters. Useful for pre-staging hardware or re-imaging existing nodes.',
  },
  {
    id: 'imaging',
    name: 'Pod Imaging',
    description: 'Pod workflow combining node imaging and cluster creation',
    category: 'Pod Operations',
    icon: 'Layers',
    configFile: 'pod-deploy.yml',
    details: 'Complete pod deployment workflow that images nodes and creates clusters as part of a larger pod management strategy.',
  },
  {
    id: 'site-deploy',
    name: 'Site Deploy',
    description: 'Full site deployment: imaging, cluster creation, and basic config',
    category: 'Infrastructure',
    icon: 'Globe',
    configFile: 'sites-deploy.yml',
    details: 'Comprehensive site deployment supporting multiple sites, each with their own imaging parameters, network settings, and multiple clusters.',
  },
  {
    id: 'config-cluster',
    name: 'Configure Cluster',
    description: 'Configure cluster: AD, storage, networks, NTP/DNS, HA',
    category: 'Configuration',
    icon: 'Settings',
    configFile: 'cluster-config.yml',
    details: 'Day-1 and Day-2 cluster configuration including Active Directory integration, storage containers, VLANs, NTP/DNS servers, and high-availability settings.',
  },
  {
    id: 'deploy-pc',
    name: 'Deploy Prism Central',
    description: 'Deploys Prism Central VM instances on target clusters',
    category: 'Prism Central',
    icon: 'Cloud',
    configFile: 'pc-deploy.yml',
    details: 'Deploys Prism Central VMs with configurable sizing (small/large/xlarge), CMSP microservices settings, NTP/DNS configuration, and optional multi-PC cluster setup.',
  },
  {
    id: 'config-pc',
    name: 'Configure Prism Central',
    description: 'Configures PC: AD, SAML, security policies, NKE, Objects',
    category: 'Prism Central',
    icon: 'Sliders',
    configFile: 'pc-config.yml',
    details: 'Full Prism Central configuration including Active Directory, SAML SSO, microsegmentation, NKE, Objects storage, disaster recovery, and flow security policies.',
  },
  {
    id: 'pod-config',
    name: 'Pod Config',
    description: 'Configures pod and edge site clusters at scale',
    category: 'Pod Operations',
    icon: 'GitBranch',
    configFile: 'pod-config.yml',
    details: 'Configures pod-level infrastructure for Nutanix Validated Designs managing multiple edge sites and their clusters.',
  },
  {
    id: 'deploy-management-pc',
    name: 'Deploy Management PC',
    description: 'Deploys Prism Central and NCM management instances',
    category: 'Pod Operations',
    icon: 'Monitor',
    configFile: 'pod-management-deploy.yml',
    details: 'Deploys the management plane Prism Central and NCM (Nutanix Cloud Manager) for centralized pod management.',
  },
  {
    id: 'config-management-pc',
    name: 'Configure Management PC',
    description: 'Initializes and configures Prism Central and NCM',
    category: 'Pod Operations',
    icon: 'Wrench',
    configFile: 'pod-management-config.yml',
    details: 'Post-deployment configuration of management Prism Central and NCM including registrations, policies, and cluster connections.',
  },
  {
    id: 'calm-vm-workloads',
    name: 'Calm VM Workloads',
    description: 'Creates and deploys VM workloads via Calm DSL blueprints',
    category: 'Workloads',
    icon: 'Cpu',
    configFile: 'create-vm-workloads.yml',
    details: 'Deploys application workloads using Nutanix Calm DSL blueprints across projects and clusters. Supports any DSL-defined blueprint.',
  },
  {
    id: 'calm-edgeai-vm-workload',
    name: 'Edge AI Workload',
    description: 'Deploys Edge-AI application workloads',
    category: 'Workloads',
    icon: 'Zap',
    configFile: 'edge-ai.json',
    details: 'Specialized workflow for deploying AI/ML workloads at edge sites using optimized Calm blueprints.',
  },
  {
    id: 'ndb',
    name: 'NDB Deploy',
    description: 'Deploys and configures Nutanix Database Service',
    category: 'Services',
    icon: 'Database',
    configFile: 'ndb.yml',
    details: 'Full NDB deployment including VM provisioning, compute profiles, cluster registration, and network profiles for PostgreSQL, MySQL, Oracle, SQL Server, MariaDB, and MongoDB.',
  },
]

export const SCRIPT_CATEGORIES = [
  'Authentication',
  'Networking',
  'Storage',
  'Compute',
  'Images',
  'Security',
  'Kubernetes',
  'Database',
  'Services',
  'Prism Central',
  'Prism Element',
  'System',
]

export const SCRIPTS: ScriptDef[] = [
  // Authentication & IAM
  { id: 'AddAdServerPe', name: 'Add AD Server (PE)', category: 'Authentication', description: 'Adds Active Directory server configuration to Prism Element' },
  { id: 'AddAdServerPc', name: 'Add AD Server (PC)', category: 'Authentication', description: 'Adds Active Directory server configuration to Prism Central' },
  { id: 'CreateRoleMappingPe', name: 'Create Role Mapping (PE)', category: 'Authentication', description: 'Creates AD role mappings in Prism Element' },
  { id: 'CreateRoleMappingPc', name: 'Create Role Mapping (PC)', category: 'Authentication', description: 'Creates AD role mappings in Prism Central' },
  { id: 'CreateLocalUser', name: 'Create Local User', category: 'Authentication', description: 'Creates a local user account' },
  { id: 'DeleteLocalUser', name: 'Delete Local User', category: 'Authentication', description: 'Removes a local user account' },
  { id: 'AddSamlIdp', name: 'Add SAML IDP', category: 'Authentication', description: 'Configures a SAML identity provider for SSO' },
  // Networking
  { id: 'CreateSubnetPe', name: 'Create Subnet (PE)', category: 'Networking', description: 'Creates a network subnet on Prism Element' },
  { id: 'CreateSubnetPc', name: 'Create Subnet (PC)', category: 'Networking', description: 'Creates a network subnet on Prism Central' },
  { id: 'DeleteSubnetPe', name: 'Delete Subnet (PE)', category: 'Networking', description: 'Removes a network subnet from Prism Element' },
  { id: 'CreateVpc', name: 'Create VPC', category: 'Networking', description: 'Creates a Virtual Private Cloud' },
  { id: 'UpdateDnsNtp', name: 'Update DNS/NTP', category: 'Networking', description: 'Updates DNS and NTP server configuration' },
  { id: 'EnableFlowNetworking', name: 'Enable Flow Networking', category: 'Networking', description: 'Enables Nutanix Flow networking policies' },
  // Storage
  { id: 'CreateContainer', name: 'Create Storage Container', category: 'Storage', description: 'Creates a storage container with specified settings' },
  { id: 'DeleteContainer', name: 'Delete Storage Container', category: 'Storage', description: 'Removes a storage container' },
  { id: 'CreateObjectStore', name: 'Create Object Store', category: 'Storage', description: 'Creates an S3-compatible object store' },
  { id: 'CreateBucket', name: 'Create Bucket', category: 'Storage', description: 'Creates a storage bucket in an object store' },
  // Compute & VMs
  { id: 'CreateVm', name: 'Create VM', category: 'Compute', description: 'Creates a virtual machine with specified resources' },
  { id: 'DeleteVm', name: 'Delete VM', category: 'Compute', description: 'Removes a virtual machine' },
  { id: 'PowerOnVm', name: 'Power On VM', category: 'Compute', description: 'Powers on a virtual machine' },
  { id: 'PowerOffVm', name: 'Power Off VM', category: 'Compute', description: 'Powers off a virtual machine' },
  { id: 'CloneVm', name: 'Clone VM', category: 'Compute', description: 'Creates a clone of an existing VM' },
  // Images
  { id: 'UploadImage', name: 'Upload Image', category: 'Images', description: 'Uploads a disk image to the image library' },
  { id: 'DeleteImage', name: 'Delete Image', category: 'Images', description: 'Removes an image from the image library' },
  // Security
  { id: 'CreateSecurityPolicy', name: 'Create Security Policy', category: 'Security', description: 'Creates a Flow microsegmentation security policy' },
  { id: 'CreateAddressGroup', name: 'Create Address Group', category: 'Security', description: 'Creates a network address group for security policies' },
  { id: 'CreateServiceGroup', name: 'Create Service Group', category: 'Security', description: 'Creates a service group for security policies' },
  { id: 'CreateCategory', name: 'Create Category', category: 'Security', description: 'Creates a category for VM grouping and policies' },
  { id: 'AssignCategoryToVm', name: 'Assign Category to VM', category: 'Security', description: 'Assigns a category to a virtual machine' },
  // Kubernetes (NKE)
  { id: 'CreateNkeCluster', name: 'Create NKE Cluster', category: 'Kubernetes', description: 'Creates a Nutanix Kubernetes Engine cluster' },
  { id: 'DeleteNkeCluster', name: 'Delete NKE Cluster', category: 'Kubernetes', description: 'Removes an NKE cluster' },
  { id: 'EnableNke', name: 'Enable NKE', category: 'Kubernetes', description: 'Enables Nutanix Kubernetes Engine on Prism Central' },
  // Database (NDB)
  { id: 'CreateDbServer', name: 'Create DB Server', category: 'Database', description: 'Provisions a database server VM via NDB' },
  { id: 'RegisterNdbCluster', name: 'Register NDB Cluster', category: 'Database', description: 'Registers a cluster with NDB' },
  { id: 'CreateNdbNetworkProfile', name: 'Create Network Profile (NDB)', category: 'Database', description: 'Creates a network profile in NDB' },
  // Prism Central
  { id: 'DeployPc', name: 'Deploy Prism Central', category: 'Prism Central', description: 'Deploys a Prism Central VM' },
  { id: 'RegisterPcToPe', name: 'Register PC to PE', category: 'Prism Central', description: 'Registers Prism Central with Prism Element' },
  { id: 'EnableMicrosegmentation', name: 'Enable Microsegmentation', category: 'Prism Central', description: 'Enables Flow microsegmentation on Prism Central' },
  { id: 'EnableObjects', name: 'Enable Objects', category: 'Prism Central', description: 'Enables Nutanix Objects on Prism Central' },
  { id: 'EnableDr', name: 'Enable DR', category: 'Prism Central', description: 'Enables Disaster Recovery capabilities' },
  { id: 'CreateProtectionRule', name: 'Create Protection Rule', category: 'Prism Central', description: 'Creates a VM protection rule with RPO/RTO settings' },
  { id: 'CreateRecoveryPlan', name: 'Create Recovery Plan', category: 'Prism Central', description: 'Creates a disaster recovery plan' },
  { id: 'RegisterRemoteAz', name: 'Register Remote AZ', category: 'Prism Central', description: 'Registers a remote availability zone for DR' },
  // Prism Element
  { id: 'ConfigureEula', name: 'Configure EULA', category: 'Prism Element', description: 'Accepts the EULA for a cluster' },
  { id: 'EnablePulse', name: 'Enable Pulse', category: 'Prism Element', description: 'Enables Pulse telemetry on a cluster' },
  { id: 'SetHaReservation', name: 'Set HA Reservation', category: 'Prism Element', description: 'Configures high-availability host reservation' },
  { id: 'SetRebuildCapacity', name: 'Set Rebuild Capacity', category: 'Prism Element', description: 'Configures rebuild capacity reservation' },
  { id: 'UpdateClusterName', name: 'Update Cluster Name', category: 'Prism Element', description: 'Changes the cluster display name' },
  // System
  { id: 'UpdateFoundation', name: 'Update Foundation', category: 'System', description: 'Updates Foundation on CVM nodes' },
  { id: 'UpdateNcc', name: 'Update NCC', category: 'System', description: 'Updates Nutanix Cluster Check (NCC)' },
  { id: 'RunNcc', name: 'Run NCC', category: 'System', description: 'Runs NCC health checks on a cluster' },
]

export const TIMEZONES = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Anchorage',
  'Pacific/Honolulu',
  'UTC',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Amsterdam',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Kolkata',
  'Australia/Sydney',
]

export const CREDENTIAL_KEYS = [
  'pc_user',
  'pe_user',
  'ncm_user',
  'cvm_credential',
  'admin_cred',
  'service_account_credential',
  'remote_pc_credentials',
  'infoblox_user',
]

export const AOS_VERSIONS = [
  '6.10.x',
  '6.8.x',
  '6.7.x',
  '6.5.x',
  '7.0',
]

export const PC_VERSIONS = [
  'pc.2024.3',
  'pc.2024.1',
  'pc.2023.4',
  'pc.2023.3',
  'pc.2022.9',
  'pc.2022.6',
]
