import type { WorkflowDef, ScriptDef } from './types'

export const WORKFLOWS: WorkflowDef[] = [
  {
    id: 'cluster-create',
    name: 'Cluster Create',
    description: 'Creates clusters using Foundation Central with full node imaging',
    category: 'Infrastructure',
    icon: 'Server',
    configFile: 'create_cluster.yml',
    details: 'Automates the complete cluster creation process including node discovery, AOS/AHV imaging, and cluster formation through Foundation Central. Supports both DHCP and static IP configurations.',
  },
  {
    id: 'imaging-only',
    name: 'Imaging Only',
    description: 'Images nodes without creating a cluster (bare metal prep)',
    category: 'Infrastructure',
    icon: 'HardDrive',
    configFile: 'imaging_only.yml',
    details: 'Images Nutanix nodes with the specified AOS and hypervisor versions without forming clusters. Useful for pre-staging hardware or re-imaging existing nodes.',
  },
  {
    id: 'imaging',
    name: 'Pod Imaging',
    description: 'Pod workflow combining node imaging and cluster creation',
    category: 'Pod Operations',
    icon: 'Layers',
    configFile: 'pod-deploy.yml',
    details: 'Complete pod deployment workflow that images nodes and creates clusters as part of a larger pod management strategy.',
  },
  {
    id: 'site-deploy',
    name: 'Site Deploy',
    description: 'Full site deployment: imaging, cluster creation, and basic config',
    category: 'Infrastructure',
    icon: 'Globe',
    configFile: 'sites-deploy.yml',
    details: 'Comprehensive site deployment supporting multiple sites, each with their own imaging parameters, network settings, and multiple clusters.',
  },
  {
    id: 'config-cluster',
    name: 'Configure Cluster',
    description: 'Configure cluster: AD, storage, networks, NTP/DNS, HA',
    category: 'Configuration',
    icon: 'Settings',
    configFile: 'cluster-config.yml',
    details: 'Day-1 and Day-2 cluster configuration including Active Directory integration, storage containers, VLANs, NTP/DNS servers, and high-availability settings.',
  },
  {
    id: 'deploy-pc',
    name: 'Deploy Prism Central',
    description: 'Deploys Prism Central VM instances on target clusters',
    category: 'Prism Central',
    icon: 'Cloud',
    configFile: 'pc-deploy.yml',
    details: 'Deploys Prism Central VMs with configurable sizing (small/large/xlarge), CMSP microservices settings, NTP/DNS configuration, and optional multi-PC cluster setup.',
  },
  {
    id: 'config-pc',
    name: 'Configure Prism Central',
    description: 'Configures PC: AD, SAML, security policies, NKE, Objects',
    category: 'Prism Central',
    icon: 'Sliders',
    configFile: 'pc-config.yml',
    details: 'Full Prism Central configuration including Active Directory, SAML SSO, microsegmentation, NKE, Objects storage, disaster recovery, and flow security policies.',
  },
  {
    id: 'pod-config',
    name: 'Pod Config',
    description: 'Configures pod and edge site clusters at scale',
    category: 'Pod Operations',
    icon: 'GitBranch',
    configFile: 'pod-config.yml',
    details: 'Configures pod-level infrastructure for Nutanix Validated Designs managing multiple edge sites and their clusters.',
  },
  {
    id: 'deploy-management-pc',
    name: 'Deploy Management PC',
    description: 'Deploys Prism Central and NCM management instances',
    category: 'Pod Operations',
    icon: 'Monitor',
    configFile: 'pod-management-deploy.yml',
    details: 'Deploys the management plane Prism Central and NCM (Nutanix Cloud Manager) for centralized pod management.',
  },
  {
    id: 'config-management-pc',
    name: 'Configure Management PC',
    description: 'Initializes and configures Prism Central and NCM',
    category: 'Pod Operations',
    icon: 'Wrench',
    configFile: 'pod-management-config.yml',
    details: 'Post-deployment configuration of management Prism Central and NCM including registrations, policies, and cluster connections.',
  },
  {
    id: 'calm-vm-workloads',
    name: 'Calm VM Workloads',
    description: 'Creates and deploys VM workloads via Calm DSL blueprints',
    category: 'Workloads',
    icon: 'Cpu',
    configFile: 'create-vm-workloads.yml',
    details: 'Deploys application workloads using Nutanix Calm DSL blueprints across projects and clusters. Supports any DSL-defined blueprint.',
  },
  {
    id: 'calm-edgeai-vm-workload',
    name: 'Edge AI Workload',
    description: 'Deploys Edge-AI application workloads',
    category: 'Workloads',
    icon: 'Zap',
    configFile: 'edge-ai.json',
    details: 'Specialized workflow for deploying AI/ML workloads at edge sites using optimized Calm blueprints.',
  },
  {
    id: 'ndb',
    name: 'NDB Deploy',
    description: 'Deploys and configures Nutanix Database Service',
    category: 'Services',
    icon: 'Database',
    configFile: 'ndb.yml',
    details: 'Full NDB deployment including VM provisioning, compute profiles, cluster registration, and network profiles for PostgreSQL, MySQL, Oracle, SQL Server, MariaDB, and MongoDB.',
  },
  {
    id: 'lcm-update',
    name: 'LCM Update',
    description: 'Runs lifecycle management update workflows',
    category: 'System',
    icon: 'Wrench',
    configFile: 'lcm-update.yml',
    details: 'Executes Nutanix lifecycle management update workflows using reviewed YAML inputs and approval-gated execution.',
  },
]

export const SCRIPT_CATEGORIES = [
  'Authentication',
  'Networking',
  'Storage',
  'Compute',
  'Images',
  'Security',
  'Kubernetes',
  'Database',
  'Services',
  'Prism Central',
  'Prism Element',
  'System',
]

export const SCRIPTS: ScriptDef[] = [
  // Authentication & IAM
  { id: 'AddAdServerPe', name: 'Add AD Server (PE)', category: 'Authentication', description: 'Adds Active Directory server configuration to Prism Element' },
  { id: 'AddAdServerPc', name: 'Add AD Server (PC)', category: 'Authentication', description: 'Adds Active Directory server configuration to Prism Central' },
  { id: 'CreateRoleMappingPe', name: 'Create Role Mapping (PE)', category: 'Authentication', description: 'Creates AD role mappings in Prism Element' },
  { id: 'CreateRoleMappingPc', name: 'Create Role Mapping (PC)', category: 'Authentication', description: 'Creates AD role mappings in Prism Central' },
  { id: 'CreateIdp', name: 'Create SAML IDP (PC)', category: 'Authentication', description: 'Configures a SAML identity provider in Prism Central' },
  { id: 'AddLocalUsers', name: 'Add Local Users (PC)', category: 'Authentication', description: 'Adds local IAM users in Prism Central' },
  { id: 'ImportUsers', name: 'Import Users (PC)', category: 'Authentication', description: 'Imports users into Prism Central' },
  { id: 'AddUserGroups', name: 'Add User Groups (PC)', category: 'Authentication', description: 'Adds IAM user groups in Prism Central' },
  { id: 'AddRoles', name: 'Add Roles (PC)', category: 'Authentication', description: 'Adds IAM roles in Prism Central' },
  { id: 'AddDirectoryServices', name: 'Add Directory Services (PC)', category: 'Authentication', description: 'Adds directory service objects in Prism Central' },
  // Networking
  { id: 'CreateSubnetPe', name: 'Create Subnet (PE)', category: 'Networking', description: 'Creates a network subnet on Prism Element' },
  { id: 'CreateSubnetsPc', name: 'Create Subnets (PC)', category: 'Networking', description: 'Creates network subnets on Prism Central' },
  { id: 'DeleteSubnetsPe', name: 'Delete Subnets (PE)', category: 'Networking', description: 'Removes network subnets from Prism Element' },
  { id: 'DeleteSubnetsPc', name: 'Delete Subnets (PC)', category: 'Networking', description: 'Removes network subnets from Prism Central' },
  { id: 'CreateVPC', name: 'Create VPC (PC)', category: 'Networking', description: 'Creates a Virtual Private Cloud in Prism Central' },
  { id: 'UpdateVPC', name: 'Update VPC (PC)', category: 'Networking', description: 'Updates a Virtual Private Cloud in Prism Central' },
  { id: 'DeleteVPC', name: 'Delete VPC (PC)', category: 'Networking', description: 'Deletes a Virtual Private Cloud in Prism Central' },
  { id: 'EnableNetworkController', name: 'Enable Network Controller (PC)', category: 'Networking', description: 'Enables Network Controller in Prism Central' },
  { id: 'DisableNetworkController', name: 'Disable Network Controller (PC)', category: 'Networking', description: 'Disables Network Controller in Prism Central' },
  { id: 'AddNameServersPe', name: 'Add DNS Servers (PE)', category: 'Networking', description: 'Adds DNS name servers in Prism Element' },
  { id: 'AddNameServersPc', name: 'Add DNS Servers (PC)', category: 'Networking', description: 'Adds DNS name servers in Prism Central' },
  { id: 'AddNtpServersPe', name: 'Add NTP Servers (PE)', category: 'Networking', description: 'Adds NTP servers in Prism Element' },
  { id: 'AddNtpServersPc', name: 'Add NTP Servers (PC)', category: 'Networking', description: 'Adds NTP servers in Prism Central' },
  // Storage
  { id: 'CreateContainerPe', name: 'Create Storage Container (PE)', category: 'Storage', description: 'Creates a storage container in Prism Element' },
  { id: 'DeleteContainerPe', name: 'Delete Storage Container (PE)', category: 'Storage', description: 'Removes a storage container from Prism Element' },
  { id: 'CreateObjectStore', name: 'Create Object Store (PC)', category: 'Storage', description: 'Creates an S3-compatible object store' },
  { id: 'DeleteObjectStore', name: 'Delete Object Store (PC)', category: 'Storage', description: 'Deletes an object store' },
  { id: 'CreateBucket', name: 'Create Bucket (PC)', category: 'Storage', description: 'Creates a bucket in an object store' },
  { id: 'ShareBucket', name: 'Share Bucket (PC)', category: 'Storage', description: 'Shares a bucket with users' },
  // Compute & VMs
  { id: 'CreateVmPe', name: 'Create VM (PE)', category: 'Compute', description: 'Creates virtual machines directly through Prism Element' },
  { id: 'CreateVmsPc', name: 'Create VMs (PC)', category: 'Compute', description: 'Creates virtual machines through Prism Central' },
  { id: 'DeleteVmPe', name: 'Delete VM (PE)', category: 'Compute', description: 'Deletes virtual machines directly through Prism Element' },
  { id: 'DeleteVmPc', name: 'Delete VM (PC)', category: 'Compute', description: 'Deletes virtual machines through Prism Central' },
  { id: 'PowerTransitionVmPe', name: 'Power Transition VM (PE)', category: 'Compute', description: 'Changes VM power state through Prism Element' },
  { id: 'PowerOnVmPc', name: 'Power On VM (PC)', category: 'Compute', description: 'Powers on virtual machines through Prism Central' },
  // Images
  { id: 'UploadImagePe', name: 'Upload Image (PE)', category: 'Images', description: 'Uploads disk or ISO images to Prism Element' },
  { id: 'PcImageUpload', name: 'Upload Image (PC)', category: 'Images', description: 'Uploads disk images through Prism Central' },
  { id: 'PcOVAUpload', name: 'Upload OVA (PC)', category: 'Images', description: 'Uploads OVA images through Prism Central' },
  { id: 'PcImageDelete', name: 'Delete Image (PC)', category: 'Images', description: 'Deletes disk images through Prism Central' },
  { id: 'PcOVADelete', name: 'Delete OVA (PC)', category: 'Images', description: 'Deletes OVA images through Prism Central' },
  // Security
  { id: 'CreateNetworkSecurityPolicy', name: 'Create Security Policy (PC)', category: 'Security', description: 'Creates a Flow network security policy' },
  { id: 'DeleteNetworkSecurityPolicy', name: 'Delete Security Policy (PC)', category: 'Security', description: 'Deletes a Flow network security policy' },
  { id: 'CreateAddressGroups', name: 'Create Address Groups (PC)', category: 'Security', description: 'Creates network address groups for security policies' },
  { id: 'DeleteAddressGroups', name: 'Delete Address Groups (PC)', category: 'Security', description: 'Deletes network address groups' },
  { id: 'CreateServiceGroups', name: 'Create Service Groups (PC)', category: 'Security', description: 'Creates service groups for security policies' },
  { id: 'DeleteServiceGroups', name: 'Delete Service Groups (PC)', category: 'Security', description: 'Deletes service groups' },
  { id: 'CreateCategoryPc', name: 'Create Category (PC)', category: 'Security', description: 'Creates categories for VM grouping and policies' },
  { id: 'DeleteCategoryPc', name: 'Delete Category (PC)', category: 'Security', description: 'Deletes categories in Prism Central' },
  // Kubernetes (NKE)
  { id: 'CreateKarbonClusterPc', name: 'Create NKE Cluster (PC)', category: 'Kubernetes', description: 'Creates a Nutanix Kubernetes Engine cluster' },
  { id: 'EnableNke', name: 'Enable NKE (PC)', category: 'Kubernetes', description: 'Enables Nutanix Kubernetes Engine on Prism Central' },
  // Database (NDB)
  { id: 'NdbConfig', name: 'Configure NDB', category: 'Database', description: 'Runs the NDB configuration script' },
  { id: 'RegisterInitClusterNdb', name: 'Register NDB Cluster', category: 'Database', description: 'Registers and initializes a cluster with NDB' },
  // Prism Central
  { id: 'DeployPC', name: 'Deploy Prism Central', category: 'Prism Central', description: 'Deploys a Prism Central VM' },
  { id: 'RegisterToPc', name: 'Register PE to PC', category: 'Prism Central', description: 'Registers Prism Element clusters with Prism Central' },
  { id: 'EnableMicrosegmentation', name: 'Enable Microsegmentation (PC)', category: 'Prism Central', description: 'Enables Flow microsegmentation on Prism Central' },
  { id: 'DisableMicrosegmentation', name: 'Disable Microsegmentation (PC)', category: 'Prism Central', description: 'Disables Flow microsegmentation on Prism Central' },
  { id: 'EnableObjects', name: 'Enable Objects (PC)', category: 'Prism Central', description: 'Enables Nutanix Objects on Prism Central' },
  { id: 'EnableDR', name: 'Enable DR (PC)', category: 'Prism Central', description: 'Enables Disaster Recovery capabilities' },
  { id: 'CreateProtectionPolicy', name: 'Create Protection Policy (PC)', category: 'Prism Central', description: 'Creates a VM protection policy with RPO/RTO settings' },
  { id: 'DeleteProtectionPolicy', name: 'Delete Protection Policy (PC)', category: 'Prism Central', description: 'Deletes a protection policy' },
  { id: 'CreateRecoveryPlan', name: 'Create Recovery Plan (PC)', category: 'Prism Central', description: 'Creates a disaster recovery plan' },
  { id: 'DeleteRecoveryPlan', name: 'Delete Recovery Plan (PC)', category: 'Prism Central', description: 'Deletes a disaster recovery plan' },
  { id: 'ConnectToAz', name: 'Connect Availability Zone (PC)', category: 'Prism Central', description: 'Connects a remote availability zone for DR' },
  { id: 'DisconnectAz', name: 'Disconnect Availability Zone (PC)', category: 'Prism Central', description: 'Disconnects a remote availability zone' },
  { id: 'EnableFC', name: 'Enable Foundation Central (PC)', category: 'Prism Central', description: 'Enables Foundation Central in Prism Central' },
  { id: 'GenerateFcApiKey', name: 'Generate FC API Key', category: 'Prism Central', description: 'Generates a Foundation Central API key' },
  { id: 'EnableMarketplace', name: 'Enable Marketplace (PC)', category: 'Prism Central', description: 'Enables Marketplace in Prism Central' },
  // Prism Element
  { id: 'AcceptEulaPe', name: 'Accept EULA (PE)', category: 'Prism Element', description: 'Accepts the EULA in Prism Element' },
  { id: 'AcceptEulaPc', name: 'Accept EULA (PC)', category: 'Prism Element', description: 'Accepts the EULA in Prism Central' },
  { id: 'UpdatePulsePe', name: 'Update Pulse (PE)', category: 'Prism Element', description: 'Updates Pulse settings in Prism Element' },
  { id: 'UpdatePulsePc', name: 'Update Pulse (PC)', category: 'Prism Element', description: 'Updates Pulse settings in Prism Central' },
  { id: 'HaReservation', name: 'Set HA Reservation (PE)', category: 'Prism Element', description: 'Configures high-availability host reservation' },
  { id: 'RebuildCapacityReservation', name: 'Set Rebuild Capacity (PE)', category: 'Prism Element', description: 'Configures rebuild capacity reservation' },
  { id: 'UpdateDsip', name: 'Update DSIP (PE)', category: 'Prism Element', description: 'Updates DSIP in Prism Element' },
  // System
  { id: 'UpdateCvmFoundation', name: 'Update CVM Foundation', category: 'System', description: 'Updates Foundation on CVM nodes' },
]

export const TIMEZONES = [
  'America/New_York',
  'America/Chicago',
  'America/Denver',
  'America/Los_Angeles',
  'America/Phoenix',
  'America/Anchorage',
  'Pacific/Honolulu',
  'UTC',
  'Europe/London',
  'Europe/Paris',
  'Europe/Berlin',
  'Europe/Amsterdam',
  'Asia/Tokyo',
  'Asia/Shanghai',
  'Asia/Singapore',
  'Asia/Kolkata',
  'Australia/Sydney',
]

export const CREDENTIAL_KEYS = [
  'pc_user',
  'pe_user',
  'ncm_user',
  'cvm_credential',
  'admin_cred',
  'service_account_credential',
  'remote_pc_credentials',
  'infoblox_user',
]

export const AOS_VERSIONS = [
  '6.10.x',
  '6.8.x',
  '6.7.x',
  '6.5.x',
  '7.0',
]

export const PC_VERSIONS = [
  'pc.2024.3.1.14',
  'pc.2024.3',
  'pc.2024.1',
  'pc.2023.4',
  'pc.2023.3',
  'pc.2022.9',
  'pc.2022.6',
]
