export type PostClusterControlMode = 'apply' | 'evidence' | 'manual' | 'blocked'

export interface PostClusterControl {
  id: string
  label: string
  section: string
  category: string
  entryPoint: string
  description: string
  mode: PostClusterControlMode
  risk?: 'medium' | 'high'
  requiresReview?: boolean
  command?: string
  evidenceCommand?: string
  operatorInput?: 'dns' | 'ntp' | 'dsip' | 'storage' | 'vm_networks' | 'eula' | 'ha'
}

export const POST_CLUSTER_SECTIONS = [
  'Basic Configuration',
  'Advanced Configuration',
  'Hardening / Security',
  'Certificates',
  'Monitoring',
  'DNS / Proxy',
  'Disaster Recovery',
]

export const POST_CLUSTER_CONTROLS: Record<string, PostClusterControl[]> = {
  'post-foundation-baseline': [
    {
      id: 'health_check',
      label: 'Cluster health check',
      section: 'Basic Configuration',
      category: 'Health',
      entryPoint: 'CVM SSH',
      description: 'Validate the cluster is healthy before day-1 configuration.',
      mode: 'evidence',
      evidenceCommand: 'cluster status',
    },
    {
      id: 'register_prism_central',
      label: 'Register with Prism Central',
      section: 'Basic Configuration',
      category: 'Registration',
      entryPoint: 'Prism Element',
      description: 'Register the cluster to the selected Prism Central endpoint.',
      mode: 'apply',
    },
    {
      id: 'accept_eula',
      label: 'Accept EULA',
      section: 'Basic Configuration',
      category: 'Cluster',
      entryPoint: 'Prism Element',
      description: 'Record EULA acceptance metadata and Pulse preference.',
      mode: 'apply',
      operatorInput: 'eula',
    },
    {
      id: 'update_pulse',
      label: 'Pulse setting',
      section: 'Basic Configuration',
      category: 'Cluster',
      entryPoint: 'Prism Element',
      description: 'Apply the selected Pulse participation setting.',
      mode: 'apply',
    },
    {
      id: 'ha_reservation',
      label: 'HA reservation',
      section: 'Basic Configuration',
      category: 'Availability',
      entryPoint: 'Prism Element',
      description: 'Configure VM high availability reservation.',
      mode: 'apply',
      operatorInput: 'ha',
    },
    {
      id: 'storage_containers',
      label: 'Storage containers',
      section: 'Basic Configuration',
      category: 'Storage',
      entryPoint: 'Prism Element',
      description: 'Create operator-defined storage containers.',
      mode: 'apply',
      operatorInput: 'storage',
    },
    {
      id: 'data_services_ip',
      label: 'Data services IP',
      section: 'Basic Configuration',
      category: 'Storage',
      entryPoint: 'Prism Element',
      description: 'Configure the cluster data services IP.',
      mode: 'apply',
      operatorInput: 'dsip',
    },
    {
      id: 'dns_servers',
      label: 'DNS servers',
      section: 'Basic Configuration',
      category: 'Network',
      entryPoint: 'Prism Element',
      description: 'Configure DNS server values supplied by the operator.',
      mode: 'apply',
      operatorInput: 'dns',
    },
    {
      id: 'ntp_servers',
      label: 'NTP servers',
      section: 'Basic Configuration',
      category: 'Time',
      entryPoint: 'Prism Element',
      description: 'Configure NTP server values supplied by the operator.',
      mode: 'apply',
      operatorInput: 'ntp',
    },
  ],
  'pe-monitoring-baseline': [
    {
      id: 'ncc_health_check',
      label: 'NCC health evidence',
      section: 'Monitoring',
      category: 'Health',
      entryPoint: 'CVM SSH',
      description: 'Capture NCC health evidence before or after monitoring changes.',
      mode: 'evidence',
      evidenceCommand: 'ncc health_checks run_all',
    },
    {
      id: 'smtp',
      label: 'SMTP server',
      section: 'Monitoring',
      category: 'Email',
      entryPoint: 'Prism Element',
      description: 'Plan SMTP configuration and test email evidence.',
      mode: 'manual',
      evidenceCommand: 'ncli cluster send-test-email',
    },
    {
      id: 'alert_email_contacts',
      label: 'Alert email contacts',
      section: 'Monitoring',
      category: 'Alerts',
      entryPoint: 'CVM SSH',
      description: 'Plan alert email contacts for Prism Element alerts.',
      mode: 'manual',
      command: 'ncli alert edit-alert-config email-contacts=<contacts>',
    },
    {
      id: 'snmpv3',
      label: 'SNMPv3 monitoring',
      section: 'Monitoring',
      category: 'SNMP',
      entryPoint: 'Prism Element',
      description: 'Plan SNMPv3 traps and polling configuration.',
      mode: 'manual',
    },
    {
      id: 'syslog',
      label: 'Syslog forwarding',
      section: 'Monitoring',
      category: 'Logging',
      entryPoint: 'Prism Element',
      description: 'Plan syslog forwarding for CVM and hypervisor audit events.',
      mode: 'manual',
    },
  ],
  'pe-security-hardening': [
    {
      id: 'ahv_aide',
      label: 'AHV AIDE',
      section: 'Hardening / Security',
      category: 'AHV Hardening',
      entryPoint: 'CVM SSH',
      description: 'Enable Advanced Intrusion Detection Environment for AHV hosts.',
      mode: 'manual',
      risk: 'medium',
      command: 'ncli cluster edit-hypervisor-security-params enable-aide=true',
      evidenceCommand: 'ncli cluster get-hypervisor-security-config',
    },
    {
      id: 'high_strength_passwords',
      label: 'High-strength password policy',
      section: 'Hardening / Security',
      category: 'AHV/CVM Hardening',
      entryPoint: 'CVM SSH',
      description: 'Plan high-strength password policies for hypervisor and CVM security parameters.',
      mode: 'manual',
      risk: 'medium',
      command: 'ncli cluster edit-hypervisor-security-params enable-high-strength-password=true',
      evidenceCommand: 'ncli cluster get-hypervisor-security-config',
    },
    {
      id: 'scma_schedule',
      label: 'SCMA schedule',
      section: 'Hardening / Security',
      category: 'AHV/CVM Hardening',
      entryPoint: 'CVM SSH',
      description: 'Plan the SCMA schedule for security compliance checks.',
      mode: 'manual',
      risk: 'medium',
      command: 'ncli cluster edit-hypervisor-security-params schedule=<frequency>',
      evidenceCommand: 'ncli cluster get-hypervisor-security-config',
    },
    {
      id: 'cvm_aide',
      label: 'CVM AIDE',
      section: 'Hardening / Security',
      category: 'CVM Hardening',
      entryPoint: 'CVM SSH',
      description: 'Enable Advanced Intrusion Detection Environment for CVMs.',
      mode: 'manual',
      risk: 'medium',
      command: 'ncli cluster edit-cvm-security-params enable-aide=true',
      evidenceCommand: 'ncli cluster get-cvm-security-config',
    },
    {
      id: 'snmpv3_only',
      label: 'SNMPv3-only mode',
      section: 'Hardening / Security',
      category: 'CVM Hardening',
      entryPoint: 'CVM SSH',
      description: 'Plan SNMPv3-only CVM security posture.',
      mode: 'manual',
      risk: 'medium',
      command: 'ncli cluster edit-cvm-security-params enable-snmpv3-only=true',
      evidenceCommand: 'ncli cluster get-cvm-security-config',
    },
    {
      id: 'ssh_access_controls',
      label: 'SSH access controls',
      section: 'Hardening / Security',
      category: 'Access Control',
      entryPoint: 'CVM SSH',
      description: 'Document allow/deny SSH access policy using operator-supplied management networks and jump hosts.',
      mode: 'blocked',
      risk: 'high',
      requiresReview: true,
      evidenceCommand: 'Operator-attested access policy review',
    },
    {
      id: 'cluster_lockdown',
      label: 'Cluster lockdown',
      section: 'Hardening / Security',
      category: 'Access Control',
      entryPoint: 'Prism Element',
      description: 'Plan cluster lockdown with explicit break-glass and rollback approval.',
      mode: 'blocked',
      risk: 'high',
      requiresReview: true,
      evidenceCommand: 'Operator-attested lockdown readiness review',
    },
  ],
  'pe-network-baseline': [
    {
      id: 'vm_networks',
      label: 'VM networks',
      section: 'Advanced Configuration',
      category: 'Network',
      entryPoint: 'Prism Element',
      description: 'Create operator-defined VM networks on Prism Element.',
      mode: 'apply',
      operatorInput: 'vm_networks',
    },
    {
      id: 'virtual_switch_descriptions',
      label: 'Virtual switch descriptions',
      section: 'Advanced Configuration',
      category: 'Network',
      entryPoint: 'Prism Element',
      description: 'Plan virtual switch descriptions and intended uplink purpose.',
      mode: 'manual',
    },
    {
      id: 'uplink_intent',
      label: 'Uplink intent',
      section: 'Advanced Configuration',
      category: 'Network',
      entryPoint: 'Prism Element',
      description: 'Document operator-supplied uplink intent before switch changes.',
      mode: 'manual',
    },
    {
      id: 'lacp_sequence',
      label: 'LACP sequence',
      section: 'Advanced Configuration',
      category: 'Network',
      entryPoint: 'Prism Element',
      description: 'Plan host-by-host LACP change sequencing with maintenance and health gates.',
      mode: 'blocked',
      risk: 'high',
      requiresReview: true,
      evidenceCommand: 'NCC health evidence after each host sequence',
    },
  ],
  'pe-certificate-baseline': [
    {
      id: 'generate_csr',
      label: 'Generate CSR',
      section: 'Certificates',
      category: 'TLS',
      entryPoint: 'CVM SSH',
      description: 'Plan CSR generation using operator-supplied certificate subject values.',
      mode: 'manual',
    },
    {
      id: 'import_certificate',
      label: 'Import signed certificate',
      section: 'Certificates',
      category: 'TLS',
      entryPoint: 'Prism Element',
      description: 'Plan replacement of the default SSL certificate after approval.',
      mode: 'blocked',
      risk: 'high',
      requiresReview: true,
    },
    {
      id: 'validate_certificate',
      label: 'Validate certificate',
      section: 'Certificates',
      category: 'TLS',
      entryPoint: 'Prism Element',
      description: 'Capture certificate validation evidence.',
      mode: 'evidence',
    },
  ],
  'hardware-out-of-band-baseline': [
    {
      id: 'hardware_inventory_evidence',
      label: 'Hardware inventory evidence',
      section: 'Basic Configuration',
      category: 'Hardware',
      entryPoint: 'Hardware manager',
      description: 'Capture out-of-band hardware inventory evidence.',
      mode: 'evidence',
    },
    {
      id: 'bmc_credential_rotation',
      label: 'BMC credential rotation',
      section: 'Hardening / Security',
      category: 'Hardware',
      entryPoint: 'Hardware manager',
      description: 'Plan BMC credential rotation through vendor-supported tooling.',
      mode: 'blocked',
      risk: 'high',
      requiresReview: true,
    },
    {
      id: 'bios_secure_boot_intent',
      label: 'Secure Boot intent',
      section: 'Hardening / Security',
      category: 'Hardware',
      entryPoint: 'BIOS/UEFI',
      description: 'Plan Secure Boot enablement and key enrollment through vendor-supported procedures.',
      mode: 'blocked',
      risk: 'high',
      requiresReview: true,
    },
  ],
}
